### PR TITLE
Added ability to add a different S3 url to the config

### PR DESCRIPTION
**Pull request by schinery**
Added ability to add a different S3 url to the config and use instead of the one generated, so you can then use custom S3 urls with this lib.

### CODE REVIEW

**Comment by schinery** [comment]
Note: Sorry... my editor converted the tabs/spaces in `S3Client.ts` so it looks like I changed a lot of the file, where in fact all that changed was line 18 `const url: string = GetUrl(this.config);`.

**Comment by Fausto95** [comment]
Thanks for the PR, could fix the tabs so I can merge that?

**Comment by schinery** [comment]
Fixed the tabbing in `S3Client.ts`. Might be worth you adding your preferred formatting rules to the `tslint.json` config to avoid further indent/spacing mishaps for folks with autofix/save enabled.

**Comment by Fausto95** [comment]
Yes, I'll do it!
Thanks for the PR!

**Pull request merged**
